// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package pgstore

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Country struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	NameEn    string       `json:"name_en"`
	Code      string       `json:"code"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Organization struct {
	ID        uuid.UUID      `json:"id"`
	Name      sql.NullString `json:"name"`
	CountryID sql.NullInt32  `json:"country_id"`
	OwnerID   uuid.NullUUID  `json:"owner_id"`
	Verified  sql.NullBool   `json:"verified"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}

type Session struct {
	ID           uuid.UUID    `json:"id"`
	UserID       uuid.UUID    `json:"user_id"`
	RefreshToken string       `json:"refresh_token"`
	UserAgent    string       `json:"user_agent"`
	ClientIp     string       `json:"client_ip"`
	IsBlocked    sql.NullBool `json:"is_blocked"`
	ExpiresAt    sql.NullTime `json:"expires_at"`
	CreatedAt    time.Time    `json:"created_at"`
}

type User struct {
	ID uuid.UUID `json:"id"`
	// first name
	Fname sql.NullString `json:"fname"`
	// middle name
	Mname sql.NullString `json:"mname"`
	// last name
	Lname     sql.NullString `json:"lname"`
	Email     string         `json:"email"`
	Phone     string         `json:"phone"`
	Password  string         `json:"password"`
	Birthdate sql.NullTime   `json:"birthdate"`
	CountryID sql.NullInt32  `json:"country_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}
