// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package pgstore

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Country struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	NameEn    string       `json:"name_en"`
	Code      string       `json:"code"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Organization struct {
	ID                uuid.UUID      `json:"id"`
	Name              string         `json:"name"`
	CountryID         int32          `json:"country_id"`
	OwnerID           uuid.UUID      `json:"owner_id"`
	RegistrationCode  string         `json:"registration_code"`
	RegistrationDate  time.Time      `json:"registration_date"`
	RegistrationImage sql.NullString `json:"registration_image"`
	Verified          bool           `json:"verified"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
}

type OrganizationContact struct {
	ID             uuid.UUID    `json:"id"`
	OrganizationID uuid.UUID    `json:"organization_id"`
	Name           string       `json:"name"`
	Phone          string       `json:"phone"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
}

type Session struct {
	ID           uuid.UUID    `json:"id"`
	RefreshToken string       `json:"refresh_token"`
	UserAgent    string       `json:"user_agent"`
	ClientIp     string       `json:"client_ip"`
	IsBlocked    sql.NullBool `json:"is_blocked"`
	ExpiresAt    sql.NullTime `json:"expires_at"`
	CreatedAt    time.Time    `json:"created_at"`
}

type User struct {
	ID uuid.UUID `json:"id"`
	// first name
	Fname sql.NullString `json:"fname"`
	// middle name
	Mname sql.NullString `json:"mname"`
	// last name
	Lname         sql.NullString `json:"lname"`
	Email         string         `json:"email"`
	Phone         string         `json:"phone"`
	Password      string         `json:"password"`
	Birthdate     sql.NullTime   `json:"birthdate"`
	CountryID     sql.NullInt32  `json:"country_id"`
	VerifiedEmail bool           `json:"verified_email"`
	Verified      bool           `json:"verified"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
}

type VerifyEmail struct {
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiredAt time.Time `json:"expired_at"`
	CreatedAt time.Time `json:"created_at"`
}
