// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package pgstore

import (
	"context"
)

type Querier interface {
	CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error)
	DeleteCountry(ctx context.Context, id int32) error
	GetCountryForUpdate(ctx context.Context, id int32) (Country, error)
	Read(ctx context.Context, id int32) (Country, error)
	ReadAll(ctx context.Context) ([]Country, error)
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error)
}

var _ Querier = (*Queries)(nil)
