CREATE TABLE "users" (
  "id" uuid PRIMARY KEY,
  "fname" varchar,
  "mname" varchar,
  "lname" varchar,
  "email" varchar NOT NULL,
  "phone" varchar NOT NULL,
  "password" varchar NOT NULL,
  "birthdate" timestamp,
  "country_id" int,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz,
  "deleted_at" timestamptz
);

CREATE TABLE "countries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "name_en" varchar NOT NULL,
  "code" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz,
  "deleted_at" timestamptz
);

CREATE TABLE "organizations" (
  "id" uuid PRIMARY KEY,
  "name" varchar,
  "country_id" int,
  "owner_id" uuid,
  "verified" bool DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz,
  "deleted_at" timestamptz
);

CREATE TABLE "sessions" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid UNIQUE NOT NULL,
  "refresh_token" varchar NOT NULL,
  "user_agent" varchar NOT NULL,
  "client_ip" varchar NOT NULL,
  "is_blocked" bool DEFAULT false,
  "expires_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX ON "users" ("email");

CREATE UNIQUE INDEX ON "users" ("phone");

CREATE UNIQUE INDEX ON "countries" ("name");

CREATE UNIQUE INDEX ON "countries" ("name_en");

CREATE UNIQUE INDEX ON "countries" ("code");

COMMENT ON COLUMN "users"."fname" IS 'first name';

COMMENT ON COLUMN "users"."mname" IS 'middle name';

COMMENT ON COLUMN "users"."lname" IS 'last name';

ALTER TABLE "users" ADD FOREIGN KEY ("country_id") REFERENCES "countries" ("id");

ALTER TABLE "organizations" ADD FOREIGN KEY ("country_id") REFERENCES "countries" ("id");

ALTER TABLE "organizations" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

ALTER TABLE "sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
